### ISSUE TITLE
Can't load "Newtonsoft.Json.dll" in the assembly resolver

### ISSUE THREAD

**Issue by nmagoncalves** [PrimaverabssDeveloper/ERP10Integration#10]
It's not possible to load  "Newtonsoft.Json.dll" in the assembly resolver. The project exit without notice.

**Comment by MQUELHAS** [comment]
Uncheck "Auto-generate binding redirects" option in the project properties

**Comment by nmagoncalves** [comment]
Tried before but still happens.

![image](https://user-images.githubusercontent.com/18192169/108368170-0bdd2a00-71f2-11eb-98de-f17f76d8e8f3.png)


![image](https://user-images.githubusercontent.com/18192169/108368094-fbc54a80-71f1-11eb-8fe4-932642e3ead6.png)

**Comment by MQUELHAS** [comment]
Strange, ignore that DLL in the assembly Resolver for now.

In the question i asked in the Primavera forum there was a user who commented:
_"A mim começou a acontecer apenas hoje, logo depois de actualizar para a última versão, e nem sequer fiz alteração nenhuma, foi do tipo: de manhã estava tudo bem, à tarde actualizei o Primavera para a última versão, sem fazer mais nada, logo depois já não corria. E realmente verifiquei que tinha a ver com a versão 11 e 12 do Newtonsoft, ao colocar a versão 12 (fui buscar uma que tinha noutro projecto) na pasta dos meus desenvolvimentos, e com a 11 na pasta Apl do Primavera, deixei de ter o problema, mas não é uma solução que me agrade muito."_

**Comment by NunoPeixotoPrimavera** [comment]
Caros, se tiverem assemblybinding no ficheiro ***.exe.config da vossa aplicação, alterem esta entrada para o que lhes vou colocar aqui:
```
<dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="11.0.0.0" />
</dependentAssembly>
```
Validem se resolve.

**Comment by MQUELHAS** [comment]
@NunoPeixotoPrimavera funciona. Obrigado.

**Comment by nmagoncalves** [comment]
@NunoPeixotoPrimavera, resolvido.

Obrigado!
