### ISSUE TITLE
Métodos referenciados no código que aparentemente não existem ou mudaram de nome

### ISSUE THREAD

**Issue by boossss** [PrimaverabssDeveloper/ERP10Integration#3]
Os métodos Initialize e LoadExtensions do ExtensibilityService parecem não existir

![image](https://user-images.githubusercontent.com/7987879/49145877-bb1f4500-f2f8-11e8-96a7-5feb39bc5284.png)

**Comment by flaviojrjardim** [comment]
@boossss Esses métodos estão adaptados a linha do mercado **GR**. Se atualizar para essa versão, deixará de ter esses erros. 
Obrigado!
