### ISSUE TITLE
Too much time to update customer data

### ISSUE THREAD

**Issue by BrnPer** [PrimaverabssDeveloper/ERP10Integration#6]
I'm using Primavera ERP API. I'm trying to update a customer data, but it takes about 2-3 minutes per customer to update... is it a normal thing? Or am I doing something wrong?

**Comment by brunobola** [comment]
Hello @BrnPer try using your code with this option:

```
var ERP = new ErpBS();

ERP.AbreEmpresaTrabalho(...);

//This Option improves performance
ERP.CacheActiva = false;

```

**Comment by BrnPer** [comment]
We get a message saying this option isn't supported by the language...

**Comment by Ssereno** [comment]
Hello @BrnPer i recomend you to use the developer network forum for this questions https://developers.primaverabss.com/
